name: _flutter_packages

environment:
  sdk: ^3.7.0-0

workspace:
  - packages/flutter
  - packages/flutter/test_private
  - packages/flutter/test_private/test
  - packages/flutter_driver
  - packages/flutter_goldens
  - packages/flutter_localizations
  - packages/flutter_test
  - packages/flutter_web_plugins
  - packages/fuchsia_remote_debug_protocol
  - packages/integration_test

dependencies:
  args: 2.7.0
  async: 2.13.0
  boolean_selector: 2.1.2
  characters: 1.4.0
  clock: 1.1.2
  collection: 1.19.1
  crypto: 3.0.6
  fake_async: 1.3.3
  file: 7.0.1
  intl: 0.20.2
  leak_tracker: 11.0.1
  leak_tracker_flutter_testing: 3.0.10
  leak_tracker_testing: 3.0.2
  matcher: 0.12.17
  material_color_utilities: 0.11.1
  meta: 1.16.0
  path: 1.9.1
  platform: 3.1.6
  process: 5.0.3
  process_runner: 4.2.0
  source_span: 1.10.1
  stack_trace: 1.12.1
  stream_channel: 2.1.4
  string_scanner: 1.4.1
  sync_http: 0.3.1
  term_glyph: 1.2.2
  test_api: 0.7.4
  typed_data: 1.4.0
  vector_math: 2.1.4
  vm_service: 15.0.0
  webdriver: 3.1.0

dev_dependencies:
  _fe_analyzer_shared: 82.0.0
  analyzer: 7.4.4
  cli_config: 0.2.0
  convert: 3.1.2
  coverage: 1.13.0
  frontend_server_client: 4.0.0
  glob: 2.1.3
  http_multi_server: 3.2.2
  http_parser: 4.1.2
  io: 1.0.5
  js: 0.7.2
  logging: 1.3.0
  mime: 2.0.0
  node_preamble: 2.0.2
  package_config: 2.2.0
  pool: 1.5.1
  pub_semver: 2.2.0
  shelf: 1.4.2
  shelf_packages_handler: 3.0.2
  shelf_static: 1.1.3
  shelf_web_socket: 2.0.1
  source_map_stack_trace: 2.1.2
  source_maps: 0.10.13
  test: 1.25.15
  test_core: 0.6.8
  watcher: 1.1.1
  web: 1.1.1
  web_socket: 1.0.0
  web_socket_channel: 3.0.3
  webkit_inspection_protocol: 1.2.1
  yaml: 3.1.3
